# openapi2-run.yaml
swagger: '2.0'
info:
  title: sample
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /ping:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://hello-ztn77q7jxa-uc.a.run.app
      responses:
        '200':
          description: A successful response
          schema:
            type: string
